"""Reviewed certificate, data-service, and load-balancer change plans."""

# ruff: noqa: E501

from remy.recommendations.plans import ChangePlan

SERVICE_PLANS = {
    "acm_certificates_expiration_check": ChangePlan(
        what="Prowler observed an expired certificate or one within the configured expiry threshold.",
        why="Expired certificates can interrupt TLS connections and service availability.",
        change="Determine whether the certificate is ACM-issued or imported. Repair validation and managed-renewal prerequisites for eligible ACM certificates; obtain and securely reimport renewed material for imported certificates. Update certificate associations only where needed.",
        impact="Certificate replacement can break hostnames, trust chains, or pinned clients. Keep private keys out of reports, source control, and Terraform inputs that would persist them in state.",
        context="certificate issuer and type, expiry, renewal status, DNS validation, domain control, all service associations, trust chain, and endpoint ownership.",
        verify="Verify the certificate actually served by every endpoint, hostname and chain validation, expiry, and renewal monitoring after the change.",
        reference="https://docs.aws.amazon.com/acm/latest/userguide/managed-renewal.html",
        caveat="The default days_to_expire_threshold is seven; the pinned check normally considers in-use certificates and can include unused certificates when configured. It does not verify endpoint deployment.",
        status="manual_action",
    ),
    "apigateway_restapi_logging_enabled": ChangePlan(
        what="Prowler observed a REST API stage without its collected logging flag enabled.",
        why="Stage execution logs support investigation of API processing failures and behavior.",
        change="Configure the regional API Gateway CloudWatch role and aws_api_gateway_method_settings logging_level as ERROR or INFO for the approved stage and methods. Manage retention and access on the resulting log groups; review access logging separately.",
        impact="Logs add cost and can expose sensitive request metadata. Keep data tracing disabled unless explicitly justified; account-level logging-role changes affect other APIs in the Region.",
        context="API ID and stage, method overrides, regional account logging role, STS availability, destinations, retention, access controls, and sensitive-data handling.",
        verify="Exercise representative requests and errors, confirm stage/method coverage and delivery, and inspect approved test records for unintended sensitive content.",
        reference="https://docs.aws.amazon.com/apigateway/latest/developerguide/rest-api-execution-logging.html",
        caveat="The pinned check tests the collected stage.logging flag, not completeness of access logs, method coverage, retention, or safe log content.",
    ),
    "eks_cluster_kms_cmk_encryption_in_secrets_enabled": ChangePlan(
        what="Prowler did not observe an explicit encryptionConfig on the EKS cluster.",
        why="An explicit customer KMS key provides key-policy control. Its absence does not prove unencrypted Kubernetes data on modern EKS.",
        change="Confirm Kubernetes version and default encryption behavior. If customer key control is required, review an encryption_config provider key on the owning aws_eks_cluster and the supported association workflow, including handling of existing data.",
        impact="Key-policy errors can disrupt control-plane data access. Key association and replacement constraints require a recovery plan; do not rotate by substituting an arbitrary key ARN.",
        context="Kubernetes version, existing encryption configuration, approved key ownership, KMS permissions, grants, key lifecycle, existing-data migration, cluster owner, and recovery requirements.",
        verify="Confirm the effective encryption provider and key access and validate API reads/writes and the supported existing-data migration procedure without exporting secret values.",
        reference="https://docs.aws.amazon.com/eks/latest/userguide/envelope-encryption.html",
        caveat="The pinned check tests only encryptionConfig presence. EKS 1.28 and later provides default envelope encryption for all Kubernetes API data, so the scanner wording must not be read as proof of plaintext secrets.",
    ),
    "elb_logging_enabled": ChangePlan(
        what="Prowler did not observe access logging enabled for the Classic Load Balancer.",
        why="Access logs support traffic analysis and incident investigation.",
        change="Configure access_logs on the owning aws_elb using an approved S3 destination and prefix, with the required regional delivery policy, compatible encryption, retention, and reader access.",
        impact="Delivery can fail with an incompatible bucket policy or encryption setting. Logs add storage cost and retain client/request metadata.",
        context="load-balancer Region, bucket ownership, prefix, delivery permissions, supported encryption, retention, and existing logging configuration.",
        verify="Confirm the delivery test succeeds and representative real requests appear in the destination with intended retention and reader permissions.",
        reference="https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-access-logs.html",
        caveat="The pinned check tests the collected access_logs flag, not recent delivery or completeness of recorded requests.",
    ),
    "elb_ssl_listeners": ChangePlan(
        what="Prowler observed a Classic Load Balancer listener whose protocol is neither SSL nor HTTPS.",
        why="TLS termination at the load balancer can protect client traffic, but the correct design depends on where encryption terminates.",
        change="Review every listener and backend protocol. For load-balancer TLS termination, update the owning aws_elb listener with a validated certificate and approved security policy; retain documented TCP pass-through only when encryption is verified at its endpoint.",
        impact="Changing protocols can break clients, health checks, proxy behavior, or mutual TLS. Classic Load Balancers do not support SNI; certificate names must cover the required endpoints.",
        context="listener and backend ports/protocols, TLS termination point, certificates, hostnames, security policies, health checks, mutual TLS, and client compatibility.",
        verify="Verify client and backend transport independently, inspect the served certificate and negotiated TLS, and test application and health-check behavior.",
        reference="https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-https-load-balancers.html",
        caveat="The pinned check flags TCP even when it carries TLS pass-through. It does not inspect payload encryption or the backend connection.",
    ),
    "elbv2_deletion_protection": ChangePlan(
        what="Prowler observed deletion protection disabled on the load balancer.",
        why="Deletion protection prevents accidental removal through the service API while it remains enabled.",
        change="Set enable_deletion_protection=true on the existing owning aws_lb resource and update the approved replacement and teardown procedure.",
        impact="Planned deletion or replacement will fail until protection is deliberately disabled. This does not prevent listener edits or all service disruption.",
        context="load-balancer identity and type, owner, lifecycle, replacement automation, and teardown requirements.",
        verify="Read back the effective deletion-protection attribute and review the lifecycle procedure; do not attempt a production deletion as a test.",
        reference="https://docs.aws.amazon.com/elasticloadbalancing/latest/application/edit-load-balancer-attributes.html",
        caveat="The pinned check tests the collected deletion_protection string for true and does not assess other resilience controls.",
    ),
    "elbv2_logging_enabled": ChangePlan(
        what="Prowler did not observe the load balancer's S3 access-log attribute enabled.",
        why="Supported access logs help investigate requests or TLS connections, with coverage depending on load-balancer type.",
        change="Identify the actual load-balancer type, then configure supported access_logs on the owning aws_lb with a reviewed destination, prefix, bucket policy, compatible encryption, and retention. Assess other log delivery mechanisms separately.",
        impact="ALB and NLB capabilities and encryption requirements differ. Legacy NLB access logs require a TLS listener and cover TLS requests; enabling the flag alone does not capture all protocols.",
        context="load-balancer type, listeners, S3 delivery attributes, existing enhanced logging, bucket and key policies, Region, retention, and cost.",
        verify="Confirm supported traffic is delivered, investigate delivery errors, and record which protocols and requests remain outside log coverage.",
        reference="https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-access-logs.html",
        caveat="The pinned implementation tests access_logs equal to true; despite its ALB wording, determine the actual resource type from current configuration.",
    ),
    "redshift_cluster_audit_logging": ChangePlan(
        what="Prowler observed external audit logging disabled for the Redshift cluster.",
        why="Exported connection, user, and activity logs support investigations beyond internal system tables.",
        change="Configure aws_redshift_logging for the approved S3 or CloudWatch destination. When user activity is required, enable enable_user_activity_logging in the owning parameter group and select the required log exports.",
        impact="Activity logs can contain sensitive query text and add storage cost. Destination permissions and parameter-group changes require review; enabling exports alone does not enable user activity logging.",
        context="cluster and parameter-group ownership, log types, destination, roles and policies, encryption, retention, query sensitivity, and readers.",
        verify="Generate approved test connections and queries, confirm each selected log type arrives, and verify retention and authorized access.",
        reference="https://docs.aws.amazon.com/redshift/latest/mgmt/db-auditing.html",
        caveat="The pinned check tests logging_enabled only; it does not prove user activity logging, delivery health, or retention.",
    ),
    "redshift_cluster_automated_snapshot": ChangePlan(
        what="Prowler did not observe the collected automated-snapshot setting enabled.",
        why="Automated snapshots support recovery only when their frequency, retention, and restore procedure meet workload requirements.",
        change="Set an approved nonzero automated_snapshot_retention_period on the owning aws_redshift_cluster and reconcile any snapshot schedule, copy policy, KMS dependencies, and manual retention requirements.",
        impact="Snapshots and copies add cost. Disabling automated snapshots deletes existing automated snapshots; RA3 cannot disable them. Avoid a rollback that sets retention to zero.",
        context="node type, snapshot retention and schedule, recent successful snapshots, cross-Region copies, key access, recovery objectives, and cluster ownership.",
        verify="Confirm successful automated snapshots and rehearse restoration to an isolated cluster, checking data, settings, key access, and measured recovery time.",
        reference="https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-snapshots.html",
        caveat="The pinned check tests cluster_snapshots truthiness, not recent successful recovery points or tested restoration.",
    ),
    "redshift_cluster_public_access": ChangePlan(
        what="Prowler observed a public endpoint, a public subnet, and an internet-open TCP security-group rule on a Redshift cluster.",
        why="These combined signals warrant review of database exposure and intended clients.",
        change="Validate private client paths, then set publicly_accessible=false on the owning aws_redshift_cluster and narrow the associated security-group rules. Plan subnet or cluster migration where needed.",
        impact="Network changes can break BI tools, ETL, administration, or vendor integrations. Confirm the actual database port: the pinned rule test is not limited to that port.",
        context="endpoint and database port, subnet routes, all security groups, private connectivity, client allowlists, data classification, and current ownership.",
        verify="Test authorized clients and denied external reachability on the actual port; review connection telemetry for unexpected access.",
        reference="https://docs.aws.amazon.com/redshift/latest/mgmt/managing-clusters-vpc.html",
        caveat="The pinned compound check can pass when dependency inventory is missing and checks any public TCP rule. It is not proof of complete isolation or successful database access.",
    ),
    "sagemaker_notebook_instance_encryption_enabled": ChangePlan(
        what="Prowler did not observe an explicit KMS key ID on the notebook instance.",
        why="An explicitly selected key supports customer key governance. Its absence does not mean SageMaker notebook volumes are unencrypted.",
        change="Confirm whether customer key control is required. If so, plan an aws_sagemaker_notebook_instance replacement with an approved kms_key_id, preserve notebook data securely, and restore all network, role, lifecycle, and storage settings.",
        impact="Replacement can interrupt sessions and lose local data unless migrated. Key permissions must permit required service access, and retained data continues to depend on its encryption key.",
        context="notebook owner, key policy, local data and backups, lifecycle scripts, execution role, network configuration, repositories, and replacement procedure.",
        verify="Validate restored notebooks and data, application dependencies, key access, and the new instance's key ID before approved source retirement.",
        reference="https://docs.aws.amazon.com/sagemaker/latest/dg/encryption-at-rest-nbi.html",
        caveat="The pinned check tests kms_key_id presence. AWS documents system-managed encryption of OS and ML data volumes when a customer key is not specified.",
    ),
    "sagemaker_notebook_instance_without_direct_internet_access_configured": ChangePlan(
        what="Prowler observed direct internet access enabled for the notebook instance.",
        why="Disabling the service-managed internet path allows outbound access to be governed through the customer's VPC.",
        change="Plan the notebook's approved VPC, security groups, service endpoints and controlled outbound path, then set direct_internet_access=Disabled in its owning configuration, reviewing the plan for replacement and migrating local data if required.",
        impact="Package downloads, repositories, S3 access, and APIs can fail without replacement connectivity. Disabling this setting does not block internet egress through a customer-managed NAT path.",
        context="notebook data, current VPC and security groups, DNS, endpoints, NAT or proxy, lifecycle scripts, dependencies, and replacement behavior.",
        verify="Test required notebook operations and service access and confirm outbound traffic follows the approved VPC path.",
        reference="https://docs.aws.amazon.com/sagemaker/latest/dg/appendix-notebook-and-internet-access.html",
        caveat="The pinned check distinguishes Enabled, Disabled, and unread configuration; unread DirectInternetAccess produces MANUAL.",
    ),
    "secretsmanager_automatic_rotation_enabled": ChangePlan(
        what="Prowler observed automatic rotation disabled for a secret.",
        why="A working rotation process limits credential lifetime while keeping the target service and its consumers synchronized.",
        change="Identify the managing service and supported rotation strategy. Configure managed rotation there, or a tested Lambda rotation function with aws_secretsmanager_secret_rotation, approved schedule, permissions, and network access.",
        impact="Rotation changes live credentials and can break cached clients. Initial rotation behavior, partial failure recovery, and staged versions require testing; never put secret values in generated reports or Terraform.",
        context="secret metadata and owner, target service, consumers and caching, managed versus Lambda rotation, function ownership, IAM/KMS, network, schedule, and rollback procedure.",
        verify="Have the authorized owner test create, set, test, and finish stages and client credential refresh in a safe environment, then monitor successful production rotation without exposing values.",
        reference="https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotate-secrets_lambda-functions.html",
        caveat="The pinned check tests rotation_enabled only. It does not establish recent success, an appropriate interval, or consumer compatibility.",
    ),
    "sns_topics_kms_encryption_at_rest_enabled": ChangePlan(
        what="Prowler did not observe a KMS key configured on the SNS topic.",
        why="SNS server-side encryption protects message bodies at rest; transport and subscriber security are separate controls.",
        change="Select a compatible key and set kms_master_key_id on the owning aws_sns_topic. Review every publisher, including AWS services, and provide required KMS permissions and topic-policy conditions.",
        impact="A wrong key policy can stop alarm and service notifications. Encryption adds key dependency and cost and does not encrypt all message metadata or downstream deliveries.",
        context="topic owner and Region, key and topic policies, AWS-service and application publishers, subscribers, dead-letter handling, monitoring, and costs.",
        verify="Publish through every intended integration and confirm subscriber delivery and failure monitoring, including the alarm path if the topic carries security alerts.",
        reference="https://docs.aws.amazon.com/sns/latest/dg/sns-key-management.html",
        caveat="The pinned check tests kms_master_key_id presence, not key policy correctness, customer ownership, or successful delivery.",
    ),
}
